name: Lint and Format

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.5

      - name: Install linters
        run: |
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Format code
        run: go fmt ./...

      - name: Fix imports
        run: goimports -w .

      - name: Run static analysis
        run: go vet ./...

      - name: Tidy up dependencies
        run: go mod tidy

      - name: Check for changes after formatting
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected after formatting or linting."
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore: auto-fix issues with formatting or linting"
            git push
          else
            echo "No changes to commit."
          fi
